# How to Calculate Principal Component Analysis (PCA) from Scratch in Python

An important machine learning method for dimensionality reduction is called Principal Component Analysis.

It is a method that uses simple matrix operations from linear algebra and statistics to calculate a projection of the original data into the same number or fewer dimensions.

In this tutorial, you will discover the Principal Component Analysis machine learning method for dimensionality reduction and how to implement it from scratch in Python.

After completing this tutorial, you will know:

* The procedure for calculating the Principal Component Analysis and how to choose principal components.
* How to calculate the Principal Component Analysis from scratch in NumPy.
* How to calculate the Principal Component Analysis for reuse on more data in scikit-learn.

Kick-start your project with my new book [Linear Algebra for Machine Learning](https://machinelearningmastery.com/linear_algebra_for_machine_learning/)", including step-by-step tutorials and the Python source code files for all examples.

Let’s get started.

Tutorial Overview

This tutorial is divided into 3 parts; they are:

Principal Component Analysis
Manually Calculate Principal Component Analysis
Reusable Principal Component Analysis

Principal Component Analysis

Principal Component Analysis, or PCA for short, is a method for reducing the dimensionality of data.

It can be thought of as a projection method where data with m-columns (features) is projected into a subspace with m or fewer columns, whilst retaining the essence of the original data.

The PCA method can be described and implemented using the tools of linear algebra.

PCA is an operation applied to a dataset, represented by an n x m matrix A that results in a projection of A which we will call B. Let’s walk through the steps of this operation.
``` shell
     a11, a12
A = (a21, a22)
     a31, a32
 
B = PCA(A)
```
The first step is to calculate the mean values of each column.

```shell
M = mean(A)
```
or
```shell
             (a11 + a21 + a31) / 3
M(m11, m12) = (a12 + a22 + a32) / 3
```

Next, we need to center the values in each column by subtracting the mean column value.

```shell
C = A - M
```

The next step is to calculate the covariance matrix of the centered matrix C.

Correlation is a normalized measure of the amount and direction (positive or negative) that two columns change together. Covariance is a generalized and unnormalized version of correlation across multiple columns. A covariance matrix is a calculation of covariance of a given matrix with covariance scores for every column with every other column, including itself.

```shell
V = cov(C)
```

Finally, we calculate the [eigendecomposition](https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/) of the covariance matrix V. This results in a list of eigenvalues and a list of eigenvectors.

```shell
values, vectors = eig(V)
```

The eigenvectors represent the directions or components for the reduced subspace of B, whereas the eigenvalues represent the magnitudes for the directions. For more on this topic, see the post:

* [Gentle Introduction to Eigendecomposition, Eigenvalues, and Eigenvectors for Machine Learning](https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/)

The eigenvectors can be sorted by the eigenvalues in descending order to provide a ranking of the components or axes of the new subspace for A.

If all eigenvalues have a similar value, then we know that the existing representation may already be reasonably compressed or dense and that the projection may offer little. If there are eigenvalues close to zero, they represent components or axes of B that may be discarded.

A total of m or less components must be selected to comprise the chosen subspace. Ideally, we would select k eigenvectors, called principal components, that have the k largest eigenvalues.

```shell
B = select(values, vectors)
```

Other matrix decomposition methods can be used such as Singular-Value Decomposition, or SVD. As such, generally the values are referred to as singular values and the vectors of the subspace are referred to as principal components.

Once chosen, data can be projected into the subspace via matrix multiplication.

```shell
P = B^T . A
```

Where A is the original data that we wish to project, B^T is the transpose of the chosen principal components and P is the projection of A.

This is called the covariance method for calculating the PCA, although there are alternative ways to to calculate it.

# Manually Calculate Principal Component Analysis

There is no pca() function in NumPy, but we can easily calculate the Principal Component Analysis step-by-step using NumPy functions.

The example below defines a small 3×2 matrix, centers the data in the matrix, calculates the covariance matrix of the centered data, and then the eigendecomposition of the covariance matrix. The eigenvectors and eigenvalues are taken as the principal components and singular values and used to project the original data.

In [7]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print('Array A = \n {}'.format(A))
# calculate the mean of each column
M = mean(A.T, axis=1)
print('\n mean of each column, M = \n {}'.format(M))
# center columns by subtracting column means
C = A - M
print('\n subtracting column means, C = \n {}'.format(C))
# calculate covariance matrix of centered matrix
V = cov(C.T)
print('\n covariance matrix of C, V = \n {}'.format(V))
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print('\n  eigenvectors = \n {}'.format(vectors))
print('\n  eigenvalues = \n {}'.format(values))
# project data
P = vectors.T.dot(C.T)
print('\n  proyections, P = \n {}'.format(P.T))

Array A = 
 [[1 2]
 [3 4]
 [5 6]]

 mean of each column, M = 
 [3. 4.]

 subtracting column means, C = 
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

 covariance matrix of C, V = 
 [[4. 4.]
 [4. 4.]]

  eigenvectors = 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

  eigenvalues = 
 [8. 0.]

  proyections, P = 
 [[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


# Reusable Principal Component Analysis

We can calculate a Principal Component Analysis on a dataset using the PCA() class in the scikit-learn library. The benefit of this approach is that once the projection is calculated, it can be applied to new data again and again quite easily.

When creating the class, the number of components can be specified as a parameter.

The class is first fit on a dataset by calling the fit() function, and then the original dataset or other data can be projected into a subspace with the chosen number of dimensions by calling the transform() function.

Once fit, the eigenvalues and principal components can be accessed on the PCA class via the explained_variance_ and components_ attributes.

The example below demonstrates using this class by first creating an instance, fitting it on a 3×2 matrix, accessing the values and vectors of the projection, and transforming the original data.

In [9]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print('Array A = \n {}'.format(A))
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print('\n  eigenvectors = \n {}'.format(pca.components_))
print('\n  eigenvalues = \n {}'.format(pca.explained_variance_))
# transform data
B = pca.transform(A)
print('\n  proyections, P = \n {}'.format(B))

Array A = 
 [[1 2]
 [3 4]
 [5 6]]

  eigenvectors = 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

  eigenvalues = 
 [8. 0.]

  proyections, P = 
 [[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


# Extensions

This section lists some ideas for extending the tutorial that you may wish to explore.

* Re-run the examples with your own small contrived matrix values.
* Load a dataset and calculate the PCA on it and compare the results from the two methods.
* Search for and locate 10 examples where PCA has been used in machine learning papers.

If you explore any of these extensions, I’d love to know.

# Further Reading

This section provides more resources on the topic if you are looking to go deeper.

# Books

* Section 7.3 Principal Component Analysis (PCA by the SVD), [Introduction to Linear Algebra](https://amzn.to/2CZgTTB), Fifth Edition, 2016.
* Section 2.12 Example: [Principal Components Analysis](https://amzn.to/2B3MsuU), Deep Learning, 2016.

# API
* [numpy.mean() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html)
* [numpy.cov() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cov.html)
* [numpy.linalg.eig() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html)
* [sklearn.decomposition.PCA API](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html)

# Articles
* [Principal component analysis on Wikipedia](https://en.wikipedia.org/wiki/Principal_component_analysis)
* [Covariance matrix](https://en.wikipedia.org/wiki/Covariance_matrix)

# Tutorials
* [Principal Component Analysis with numpy](https://glowingpython.blogspot.com.au/2011/07/principal-component-analysis-with-numpy.html), 2011.
* [PCA and image compression with numpy](https://glowingpython.blogspot.com.au/2011/07/pca-and-image-compression-with-numpy.html), 2011.
* [Implementing a Principal Component Analysis (PCA)](http://sebastianraschka.com/Articles/2014_pca_step_by_step.html), 2014.

# Summary

In this tutorial, you discovered the Principal Component Analysis machine learning method for dimensionality reduction.

Specifically, you learned:

* The procedure for calculating the Principal Component Analysis and how to choose principal components.
* How to calculate the Principal Component Analysis from scratch in NumPy.
* How to calculate the Principal Component Analysis for reuse on more data in scikit-learn.

Do you have any questions?
Ask your questions in the comments below and I will do my best to answer.